# Generated by Django 6.0.3 on 2026-03-21 03:01

import django.core.validators
import django.db.models.deletion
import oyk.core.fields
import oyk.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OykUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Slug is auto')),
                ('abbr', models.CharField(max_length=3, verbose_name='Abbreviation')),
                ('is_abbr_auto', models.BooleanField(default=True, verbose_name='Abbreviation is auto')),
                ('logo', oyk.core.fields.OykImageField(blank=True, max_length=1200, null=True, upload_to='w/u/l', validators=[oyk.core.validators.oyk_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Logo')),
                ('cover', oyk.core.fields.OykImageField(blank=True, max_length=1200, null=True, upload_to='w/u/c', validators=[oyk.core.validators.oyk_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Cover')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Administrators'), (3, 'Moderators'), (4, 'Members'), (5, 'Visitors'), (6, 'Public')], default=1, verbose_name='Visibility')),
                ('is_mod_blog_active', models.BooleanField(default=False, verbose_name='Mod Blog Active')),
                ('mod_blog_settings', models.JSONField(verbose_name='Mod Blog Settings')),
                ('is_mod_agenda_active', models.BooleanField(default=False, verbose_name='Mod Agenda Active')),
                ('mod_agenda_settings', models.JSONField(verbose_name='Mod Agenda Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universes', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Universe',
                'verbose_name_plural': 'Universes',
                'db_table': 'oyk_world_universes',
            },
        ),
        migrations.CreateModel(
            name='OykTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('c_primary', models.CharField(max_length=7, verbose_name='Primary Colour')),
                ('c_primary_fg', models.CharField(max_length=7, verbose_name='Foreground Primary Colour')),
                ('variables', models.JSONField(verbose_name='Variables')),
                ('stylesheet', models.TextField(blank=True, null=True, verbose_name='Stylesheet')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='oyk_world.oykuniverse', verbose_name='Universe')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'db_table': 'oyk_world_themes',
            },
        ),
        migrations.CreateModel(
            name='OykRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Administrator'), (3, 'Moderator'), (4, 'Member'), (5, 'Visitor'), (6, 'Public')], default=5, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universe_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='oyk_world.oykuniverse', verbose_name='Universe')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'oyk_world_roles',
                'ordering': ['role'],
            },
        ),
        migrations.AddIndex(
            model_name='oykuniverse',
            index=models.Index(fields=['slug'], name='oyk_world_u_slug_73634a_idx'),
        ),
        migrations.AddIndex(
            model_name='oykuniverse',
            index=models.Index(fields=['owner'], name='oyk_world_u_owner_i_25c54b_idx'),
        ),
        migrations.AddIndex(
            model_name='oyktheme',
            index=models.Index(fields=['universe'], name='oyk_world_t_univers_f380e2_idx'),
        ),
        migrations.AddIndex(
            model_name='oyktheme',
            index=models.Index(fields=['universe', 'is_active'], name='oyk_world_t_univers_04b67d_idx'),
        ),
        migrations.AddConstraint(
            model_name='oykrole',
            constraint=models.UniqueConstraint(fields=('universe', 'user'), name='unique_role_per_universe'),
        ),
    ]
