# Generated by Django 6.0.3 on 2026-03-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyk_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oykuniverse',
            name='mod_agenda_settings',
            field=models.JSONField(blank=True, null=True, verbose_name='Mod Agenda Settings'),
        ),
        migrations.AlterField(
            model_name='oykuniverse',
            name='mod_blog_settings',
            field=models.JSONField(blank=True, null=True, verbose_name='Mod Blog Settings'),
        ),
    ]
