"""empty message

Revision ID: 7bac192e4a3e
Revises: c8605493828e
Create Date: 2025-08-08 14:00:05.309763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bac192e4a3e'
down_revision = 'c8605493828e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oyk_world_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['oyk_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oyk_world_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_world_areas_id'), ['id'], unique=False)

    op.create_table('oyk_world_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('world_area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_area_id'], ['oyk_world_areas.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['oyk_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oyk_world_sectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oyk_world_sectors_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_world_sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_world_sectors_id'))

    op.drop_table('oyk_world_sectors')
    with op.batch_alter_table('oyk_world_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oyk_world_areas_id'))

    op.drop_table('oyk_world_areas')
    # ### end Alembic commands ###
