"""empty message

Revision ID: b08f9c2d3bf8
Revises: 0d001dbf9847
Create Date: 2025-08-05 22:04:10.906130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08f9c2d3bf8'
down_revision = '0d001dbf9847'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oyk_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
