# Generated by Django 6.0.3 on 2026-03-19 03:04

import django.core.validators
import django.utils.timezone
import oyk.core.fields
import oyk.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OykUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Courriel')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('is_slug_auto', models.BooleanField(default=True, verbose_name='Slug is auto')),
                ('abbr', models.CharField(max_length=3, verbose_name='Abbreviation')),
                ('is_abbr_auto', models.BooleanField(default=True, verbose_name='Abbreviation is auto')),
                ('avatar', oyk.core.fields.OykImageField(blank=True, max_length=1200, null=True, upload_to='a/u/a', validators=[oyk.core.validators.oyk_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Avatar')),
                ('cover', oyk.core.fields.OykImageField(blank=True, max_length=1200, null=True, upload_to='a/u/c', validators=[oyk.core.validators.oyk_image_size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Cover')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='Timezone')),
                ('meta_bio', models.TextField(blank=True, null=True)),
                ('meta_birthday', models.DateField(blank=True, null=True)),
                ('meta_country', models.CharField(blank=True, max_length=64, null=True)),
                ('meta_job', models.CharField(blank=True, max_length=128, null=True)),
                ('meta_mood', models.CharField(blank=True, max_length=64, null=True)),
                ('meta_website', models.URLField(blank=True, max_length=255, null=True)),
                ('meta_socials', models.JSONField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('banned_reason', models.TextField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('failedlogin_at', models.DateTimeField(blank=True, null=True)),
                ('failedlogin_count', models.PositiveSmallIntegerField(default=0)),
                ('lastlogin_at', models.DateTimeField(blank=True, null=True)),
                ('lastlogin_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('lastlive_at', models.DateTimeField(blank=True, null=True)),
                ('lastlive_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'oyk_auth_users',
                'ordering': ['-created_at'],
            },
        ),
    ]
