# Generated by Django 6.0.3 on 2026-03-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyk_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oykuser',
            options={'ordering': ['-lastlive_at', '-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
